# Inception docker-compose.yml

volumes:
  wordpress-vol:
    name: wordpress-vol
    driver: local
    driver_opts:
      device: $HOME/data/wordpress-vol
      o: bind     # Bind type volume
      type: none  # Don't assume filesystem type


services:

  nginx:
    image: inception-nginx
    container_name: inception-nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - wordpress-vol:/var/www/html

  wordpress:
    image: inception-wordpress
    container_name: inception-wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress-vol:/var/www/html

  mariadb:
    image: inception-mariadb
    container_name: inception-mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    

