# Inception docker-compose.yml

services:

  nginx:
    image: inception-nginx
    container_name: inception-nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile

  wordpress:
    image: inception-wordpress
    container_name: inception-wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile

  mariadb:
    image: inception-mariadb
    container_name: inception-mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    
volumes:
  mysite-vol:

