# Inception docker-compose.yml

volumes:
  wordpressvol:
    name: wordpressvol
    driver: local
    driver_opts:
      device: $HOME/data/wordpressvol
      o: bind     # Bind type volume
      type: none  # Don't assume filesystem type

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - wordpressvol:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpressvol:/var/www/html
    depends_on:
      - mariadb
    env_file:
    - .env
    networks:
      - inception
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    restart: always

